/**
 * Created by I852780 on 06/09/2016.
 */
public class NumericRepresentation {

    public static int getSymbolNumber(char symbol){
        int i;
        for(i = 0; i < values.length; i++){
            if(values[i] == symbol)
                return i+1;
        }
        return -1;
    }

    private static char[] values = {'a',
            'e',
            'o',
            's',
            'r',
            'i',
            'd',
            'n',
            'm',
            'u',
            't',
            'c',
            'l',
            'p',
            'v',
            'h',
            'g',
            'b',
            'q',
            'i',
            'á',
            'ç',
            'â',
            'x',
            'é',
            'E',
            'j',
            'í',
            'x',
            'ó',
            'C',
            'ê',
            'à',
            'ã',
            'è',
            'z',
            'k',
            'ó',
            'ô',
            'ç',
            'ú',
            'A',
            'B',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'X',
            'W',
            'Y',
            'Z',
            'w',
            'y',
            'Ã',
            'À',
            'Â',
            'Ç',
            'É',
            'È',
            'Ê',
            'Í',
            'Ì',
            'Ô',
            'Ú',
            'Û'
    };
}
